const topics = [
    "Neural Network Potentials for Organic Chemistry",
    "Inverse Design of Molecular Libraries",
    "Machine-Learned Scoring Functions for Virtual Screening",
    "Reaction Representation Learning",
    "Low-Data / Multi-Task Learning in Chemistry",
    "Multi-Objective Optimization for Lead Discovery",
    "Uncertainty Quantification",
    "Measuring Kinetic Isotope Effects",
    "Deracemizaiton Chemistry",
    "Transition State Search Methods",
    "Substrate Scope or Condition Screening",
    "Computational Chemistry Methods for Exploring Chemical Reaction Networks",
    "Computer-Aided Retrosynthesis of Natural Products",
    "Flow Chemistry",
    "The Novelty Search Algorithm",
    "Transition State Theory",
    "Machine Learning for Excited State Molecules",
    "Retrieval-based/Retrieval-augmented Prediction for Chemistry",
    "Human-in-the-Loop Workflow for Data-driven Predictive Chemistry",
    "Ligand Field Theory",
    "Chemistry Foundation Models",
    "Challenges in Molecule/Reaction Representations (and in their Implementations)",
    "Contrastive Learning on Molecular Graphs",
    "Bayesian Neural Networks (Applied to Chemistry Domain?)",
    "Topological Deep Learning (Applications to Chemistry/Biology)",
    "Machine Learning Prediction of Reaction Mechanisms",
    "Delta Learning for Computational Chemistry",
    "Batched Optimization",
    "Search, Tree Search, and Multi-Objective Tree Search",
    "Path Integral Molecular Dynamics",
    "ML-Enhanced Kinetic Monte Carlo",
    "LLM for Chemistry",
    "Metadynamics",
    "How DFT Actually Works",
    "Hamiltonian Learning via Deep Neural Networks",
    "Markov State Models Learned from High-Dimensional Trajectories",
    "Molecular Complexity",
    "Mixture of Experts/Mixture Models",
];